#!/usr/bin/env groovy

@Library('jenkins-shared-library')
def gv

pipeline {
    agent any
    tools {
        maven 'maven-3.8'
    }
    parameters {
        choice(name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }
    stages {
        stage("init") {
            steps {
                script {
                   gv = load "Jenkinsfile-syntax/script.groovy"
                }
            }
        }
        stage("buildJar") {
            steps {
                script {
                    buildJar()
                }
            }
        }
        stage("buildImage") {
            when {
                expression {
                    params.executeTests
                }
            }
            steps {
                script {
                    buildImage 'anasm98/javmav-app-anasm:jma-anasm-1.0.3'
                    dockerLogin()
                    dockerPush 'anasm98/javmav-app-anasm:jma-anasm-1.0.3'
                }
            }
        }
        stage("deployApp") {
            steps {
                script {
                    // env.ENV = input message: "Select the environment to deploy to", ok: "Done", parameters: [choice(name: 'ONE', choices: ['dev', 'staging', 'prod'], description: '')]

                    gv.deployApp()
                    // echo "Deploying to ${ENV}"
                    echo "Deploying to production" 
                }
            }
        }
    }
}

